version: '3'

services:

  hldsAutomix:
    container_name: cs-automix-p1mp
    image: febley/counter-strike_server:latest
    restart: always
    environment:
      - PORT=27016
      - MAP=de_dust2
      - MAXPLAYERS=16
      - SV_LAN=0
    ports:
      - 27016:27016/udp
      - 27016:27016
    volumes:
      - ./server.cfg:/hlds/cstrike/server.cfg
      - ./mapcycle.txt:/hlds/cstrike/mapcycle.txt
      - ./maps/:/hlds/cstrike/maps/
      - ./publico.cfg:/hlds/cstrike/publico.cfg
      - ./cerrado.cfg:/hlds/cstrike/cerrado.cfg
      - ./vale.cfg:/hlds/cstrike/vale.cfg
      - ./practica.cfg:/hlds/cstrike/practica.cfg
      - ./rates.cfg:/hlds/cstrike/rates.cfg
      - ./addons/:/hlds/cstrike/addons/
      - ./liblist.gam:/hlds/cstrike/liblist.gam
      - ./dproto.cfg:/hlds/cstrike/dproto.cfg
      - ./practice.cfg:/hlds/cstrike/practice.cfg
      - ./pug.cfg:/hlds/cstrike/pug.cfg
