version: '3'

services:

  hlds:
    container_name: cs-dproto
    image: sebiglesias/cs1.6-server:latest
    restart: always
    environment:
      - PORT=27015
      - MAP=de_dust2
      - MAXPLAYERS=16
      - SV_LAN=0
    ports:
      - 27015:27015/udp
      - 27015:27015
