version: '3'

services:

  hlds:
    container_name: cs-con-dproto
    image: febley/counter-strike_server:latest
    restart: always
    environment:
      - PORT=27015
      - MAP=de_dust2
      - MAXPLAYERS=16
      - SV_LAN=0
    ports:
      - 27015:27015/udp
      - 27015:27015
    volumes:
      - $HOME/cs16/server.cfg:/hlds/cstrike/server.cfg
      - $HOME/cs16/mapcycle.txt:/hlds/cstrike/mapcycle.txt
      - $HOME/cs16/maps/:/hlds/cstrike/maps/
      - $HOME/cs16/publico.cfg:/hlds/cstrike/publico.cfg
      - $HOME/cs16/cerrado.cfg:/hlds/cstrike/cerrado.cfg
      - $HOME/cs16/vale.cfg:/hlds/cstrike/vale.cfg
      - $HOME/cs16/practica.cfg:/hlds/cstrike/practica.cfg
      - $HOME/cs16/rates.cfg:/hlds/cstrike/rates.cfg
      - $HOME/cs16/addons/:/hlds/cstrike/addons/
      - $HOME/cs16/liblist.gam:/hlds/cstrike/liblist.gam
      - $HOME/cs16/dproto.cfg:/hlds/cstrike/dproto.cfg

